### ISSUE TITLE
Collada Import has unexpected transformations

### ISSUE THREAD

**Issue by benjamin-heasly** [benjamin-heasly/mexximp#1]
This issue started as an email from @tlian7.

Attached I've rendered your camera example, once by importing the .blend file directly and the second time by importing the .dae file exported through Blender.  The first method works as expected, while the second method produces a black image.

From the output of the script I can see that the transforms through both method are different. From Blender we have:
```
cameraTransform =
    1.0000         0         0         0
         0   -0.0000    1.0000         0
         0   -1.0000   -0.0000         0
         0         0         0    1.0000

cubeTransform =
     1     0     0     0
     0     1     0     0
     0     0     1     0
     0   100     0     1
```

And from the Collada file we have:
```
cameraTransform =
    1.0000         0         0         0
         0    1.0000    0.0000         0
         0   -0.0000    1.0000         0
         0         0         0    1.0000

cubeTransform =
     1     0     0     0
     0     0    -1     0
     0     1     0     0
     0   100     0     1
```

I've attached the script along with the Blender and Collada file used. Do you have any ideas why this might be happening? This may explain why I haven't had any luck with rendering Collada files in the past. 

[mexximp-issue-1.zip](https://github.com/RenderToolbox/mexximp/files/569446/mexximp-issue-1.zip)

**Comment by benjamin-heasly** [comment]
Hi @tlian7.

I think this is an instance of File Format Hell.  The Collada file produced by Blender contains a "Z_UP" element, which causes Assimp to add an extra transformation to the scene's root node.  I found that if we ignore this root transformation, then the geometry comes out as expected and we don't get the blank image.

The change would be on line 69 of `transforms_fileFormatTest.m`, attached above.

```
scene = mexximpCleanImport(parentSceneFile, 'ignoreRootTransform', true);
```

I think ignoring the root node transform is a hack, which is why `mexximpCleanImport()` defaults to `'ignoreRootTransform', false`.  But maybe `true` would be a more practical default.

I think this kind of thing is confusing and annoying -- I don't know if Blender was wrong to put the "Z_UP" in the Collada file, or if Assimp is handling the "Z_UP" incorrectly.  I also don't know if this is a consistent problem that we can fix once in mexximp, or if we will have to take it scene by scene.  Collada authored by other programs might work out differently.  And then there are all the other formats that Assimp supports.

Anyway, before I change the default, could you try one or two Collada scenes and see if  `'ignoreRootTransform', true` works better?

Thanks!

**Comment by tlian7** [comment]
Hi @benjamin-heasly,

We've been using `'ignoreRootTransform', true` in our Collada scenes (authored by Blender), and so far it seems to be working as expected. I will report back if we ever find an issue with it. 

Thanks for your help!

**Comment by benjamin-heasly** [comment]
That's great to know.  Thanks.

I think we should go ahead and make this the default.  I will do that soon.

**Comment by benjamin-heasly** [comment]
Hi @tlian7,

I made a PR for this.
  https://github.com/RenderToolbox/mexximp/pull/4

It's just a one line change.  In the spirit of collaboration, could you look at the PR and go ahead and merge if it looks good to you?

Thanks!
