### ISSUE TITLE
Lengthy import of large scenes

### ISSUE THREAD

**Issue by hblasins** [benjamin-heasly/mexximp#10]
The mexximp to mPbrt conversion of large scenes is a lengthy process. Typically a large scene (0.5GB) is imported by mexximp in about 30seconds, and can take as long as 20 minutes to convert to mPbrt format.

Matlab benchmarking and timing reveals that the majority of time is spent in `mPbrtImportMexximpMaterial` function, lines 43-47. These lines seem to do nothing more but copy data.

**Comment by benjamin-heasly** [comment]
I think we made progress on this in another thread.  And if we want to make things faster, we'll have to do some significant redesign.  So I'm going to go ahead and close this one.
